package com.example.helloworld;

import java.util.logging.Logger;

public class Main {
    private static final Logger logger = Logger.getLogger(Main.class.getName());

    public static void main(String[] args) {
        Point point = new Point(1, 2);
        // Generated by Copilot
        logger.info("Point coordinates: " + point.x() + ", " + point.y());
    }
}
